<Project Sdk="Godot.NET.Sdk/4.6.0">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <Folder Include="Scripts\__Game\3-Data\Public\NewFolder\" />
    <Folder Include="Scripts\__Game\4-Logic\_Data\Production\LocalStep\" />
  </ItemGroup>
</Project>